preload = ~/.config/hypr/wallpaper.jpg

wallpaper = eDP-1,/home/fynnkunz/.config/hypr/wallpaper.jpg
wallpaper = HDMI-A-1,/home/fynnkunz/.config/hypr/wallpaper.jpg

#enable splash text rendering over the wallpaper
splash = true

#fully disable ipc
# ipc = off


