$terminal = alacritty
$fileManager = yazi

exec-once = nm-applet
exec-once = hyprpaper
exec-once = syncthing
exec-once = wired
exec-once = alacritty --daemon
exec-once = nwg-dock-hyprland -d -hd 0 -mb 10
exec-once = nwg-panel
